name: fjp-seminar-1
channels:
- menpo
- defaults
dependencies:
- ipykernel
- ipython
- matplotlib
- notebook
- numpy
- pandas
- pip
- python
- scikit-learn
- scipy
- seaborn
- setuptools
- statsmodels
